name: potatoes
description: Potatoes or french fries?
version: 2.1.0
homepage: https://www.caelis-tech.studio

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
