name: potatoes
description: Potatoes or french fries?
version: 3.0.1
homepage: https://github.com/Venusdjinni/potatoes
repository: https://github.com/Venusdjinni/potatoes
issue_tracker: https://github.com/Venusdjinni/potatoes/issues
topics: [bloc, boilerplate]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2