name: potatoes
description: Potatoes or french fries?
version: 3.0.5
homepage: https://github.com/Venusdjinni/potatoes
repository: https://github.com/Venusdjinni/potatoes
issue_tracker: https://github.com/Venusdjinni/potatoes/issues
topics: [bloc, boilerplate]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2